conf:
	clear
	curl --silent --location https://deb.nodesource.com/setup_6.x | sudo bash -
	sudo apt-get install --yes nodejs
	sudo apt-get install npm
	npm install -g gulp
conf-semantic:
	npm install semantic-ui --save